apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s-app
  template:
    metadata:
      labels:
        app: s-app
    spec:
      containers:
        - name: s-app
          image: pfa123/pfa3.0:latest
          ports:
            - containerPort: 3500

---
apiVersion: v1
kind: Service
metadata:
  name: s-app
spec:
  selector:
    app: s-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3500
      nodePort: 32000

